// The narration is generated by scripts/narrate.py, which is Python. These
// tests do not synthesise anything; they check the invariant the player depends
// on: that the timing sidecar and the sentence spans in methodology.html
// describe the same sentences, in the same order.
//
// If the audio has not been built in this checkout the tests skip rather than
// fail, so `node --test` still passes on a fresh clone.

const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const ROOT = path.join(__dirname, "..");
const SOURCE = path.join(ROOT, "methodology.html");
const TIMING = path.join(ROOT, "audio", "methodology.json");

const built = fs.existsSync(TIMING);
const source = fs.readFileSync(SOURCE, "utf8");
const spans = [...source.matchAll(/data-s="(\d+)"/g)].map((m) => Number(m[1]));

test("methodology: sentence spans are numbered 0..n-1 with no gaps or repeats", { skip: !built && "narration not built" }, () => {
  assert.ok(spans.length > 0, "no sentence spans found");
  assert.deepEqual([...spans].sort((a, b) => a - b), spans.map((_, i) => i));
});

test("narration: the timing file matches the spans in the prose", { skip: !built && "narration not built" }, () => {
  const timing = JSON.parse(fs.readFileSync(TIMING, "utf8"));
  assert.equal(timing.sentences.length, spans.length,
    "a sentence count mismatch means the audio is stale: run `make audio`");
  timing.sentences.forEach((s, i) => { assert.equal(s.i, i); });
});

test("narration: offsets increase and stay inside the recording", { skip: !built && "narration not built" }, () => {
  const timing = JSON.parse(fs.readFileSync(TIMING, "utf8"));
  let previous = -1;
  for (const s of timing.sentences) {
    assert.ok(s.t > previous, `offset ${s.t} does not advance past ${previous}`);
    assert.ok(s.t < timing.duration, `offset ${s.t} is past the end (${timing.duration})`);
    previous = s.t;
  }
});

test("narration: spans wrap no other spans", { skip: !built && "narration not built" }, () => {
  assert.equal(/<span data-s="\d+">[^<]*<span data-s=/.test(source), false,
    "nested sentence spans — narrate.py should strip old wrappers before rewriting");
});
