#!/usr/bin/env node
// Validates data/nz/parties/*.json against the schema and writes data/nz/parties.js
// (a plain script defining PARTIES_NZ) so the static page works from disk.
// Usage: node scripts/build-parties.js [--check]   (--check validates and compares only)

const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const SRC_DIR = path.join(ROOT, "data", "nz", "parties");
const OUT = path.join(ROOT, "data", "nz", "parties.js");
const { DIMENSIONS } = require(path.join(ROOT, "js", "data.js"));
const DIM_IDS = DIMENSIONS.map((d) => d.id);
const CONFIDENCE = ["high", "medium", "low"];
const REQUIRED = ["id", "name", "short", "colour", "website", "assessedAt", "rubricVersion", "status", "inParliament", "dimensions"];

function validate(party, file) {
  const errors = [];
  const err = (m) => errors.push(`${path.basename(file)}: ${m}`);
  REQUIRED.forEach((k) => { if (!(k in party)) err(`missing field ${k}`); });
  if (party.id !== path.basename(file, ".json")) err(`id "${party.id}" does not match filename`);
  if (!/^\d{4}-\d{2}-\d{2}$/.test(party.assessedAt || "")) err("assessedAt must be YYYY-MM-DD");
  if (!["draft", "reviewed"].includes(party.status)) err("status must be draft or reviewed");
  if (!/^#[0-9a-fA-F]{6}$/.test(party.colour || "")) err("colour must be a hex colour");
  const dims = party.dimensions || {};
  DIM_IDS.forEach((id) => {
    const c = dims[id];
    if (!c) { err(`missing dimension ${id}`); return; }
    if (c.score !== null && (!Number.isInteger(c.score) || c.score < -100 || c.score > 100)) err(`${id}: score must be an integer -100..100 or null`);
    if (!CONFIDENCE.includes(c.confidence)) err(`${id}: confidence must be high, medium or low`);
    if (c.score === null && c.confidence !== "low") err(`${id}: a null score must carry low confidence`);
    if (typeof c.rationale !== "string" || c.rationale.trim().length < 40) err(`${id}: rationale missing or too short`);
    if (c.score !== null) {
      if (!Array.isArray(c.sources) || c.sources.length === 0) err(`${id}: at least one source is required for a scored cell`);
      (c.sources || []).forEach((s, i) => {
        if (!s.title) err(`${id}: source ${i} has no title`);
        if (!s.url && !s.archived) err(`${id}: source ${i} needs a url or an archived path`);
        if (s.archived && !fs.existsSync(path.join(ROOT, s.archived))) err(`${id}: archived file not found: ${s.archived}`);
        if (s.date && !/^\d{4}(-\d{2}(-\d{2})?)?$/.test(s.date)) err(`${id}: source ${i} date must be YYYY, YYYY-MM or YYYY-MM-DD`);
      });
    }
  });
  Object.keys(dims).forEach((id) => { if (!DIM_IDS.includes(id)) err(`unknown dimension ${id}`); });
  return errors;
}

function main() {
  const check = process.argv.includes("--check");
  if (!fs.existsSync(SRC_DIR)) { console.error(`No party directory at ${SRC_DIR}`); process.exit(1); }
  const files = fs.readdirSync(SRC_DIR).filter((f) => f.endsWith(".json")).sort();
  const parties = [];
  let errors = [];
  for (const f of files) {
    const full = path.join(SRC_DIR, f);
    let party;
    try { party = JSON.parse(fs.readFileSync(full, "utf8")); }
    catch (e) { errors.push(`${f}: invalid JSON (${e.message})`); continue; }
    errors = errors.concat(validate(party, full));
    parties.push(party);
  }
  if (errors.length) {
    console.error("Validation failed:\n  " + errors.join("\n  "));
    process.exit(1);
  }
  const meta = {
    jurisdiction: "New Zealand",
    election: "General election, 7 November 2026",
    rubricVersion: parties.length ? parties.map((p) => p.rubricVersion).sort().pop() : "1.0",
    assessedAt: parties.length ? parties.map((p) => p.assessedAt).sort().pop() : null,
    generatedAt: new Date().toISOString().slice(0, 10),
    parties: parties.map((p) => p.id)
  };
  const body = "// Generated by scripts/build-parties.js from data/nz/parties/*.json. Do not edit by hand.\n" +
    "var PARTIES_NZ = " + JSON.stringify({ meta, parties }, null, 2) + ";\n" +
    "if (typeof module !== \"undefined\") { module.exports = PARTIES_NZ; }\n";
  if (check) {
    const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, "utf8") : "";
    // Ignore generatedAt when comparing.
    const strip = (s) => s.replace(/"generatedAt": "[^"]*"/, "");
    if (strip(current) !== strip(body)) { console.error(`${path.relative(ROOT, OUT)} is out of date; run node scripts/build-parties.js`); process.exit(1); }
    console.log(`OK: ${parties.length} parties valid, ${path.relative(ROOT, OUT)} in sync`);
    return;
  }
  fs.writeFileSync(OUT, body);
  console.log(`Wrote ${path.relative(ROOT, OUT)}: ${parties.length} parties (${parties.map((p) => p.short).join(", ")})`);
}

main();
